name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت فایل‌های پروژه
        uses: actions/checkout@v4

      - name: نصب Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'

      - name: نصب Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: بررسی نسخه Flutter
        run: flutter --version

      - name: ساخت پوشه Android
        run: flutter create --platforms=android --project-name hse_final_project .

      - name: دریافت وابستگی‌ها
        run: flutter pub get

      - name: ساخت APK
        run: flutter build apk --release

      - name: بارگذاری فایل APK
        uses: actions/upload-artifact@v4
        with:
          name: hse-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
